### ISSUE TITLE
OnAuthenticationFailed does not change Status Code

### ISSUE THREAD

**Issue by eduard-tapkey** [mihirdilip/aspnetcore-authentication-apikey#33] opened 2022-06-23 13:34 UTC
Hi,
when veryfing APIKey format and value, and the value is incorrect, I throw an exception.
This results into a problem, that HttpResponse has 500 status code.
As this happens during Authorization, I would like to return 401 instead. I figured out that the right point should be defining an event for OnAuthenticationFailed in Startup.cs . I did it based on different implementations I found online, but it is not working properly.
It returns "HttpRequestException: Error while copying content to stream" and "The response ended prematurely".

What am I doing work here as is this expected not to work?

```
OnAuthenticationFailed = context =>
{
    context.Response.StatusCode = 401;
    context.Response.ContentType = "text/plain";
    return context.Response.WriteAsync(context.Exception.Message);
 }
```

If I only change the Status code, it still returns 500.

**Comment by mihirdilip** [comment] 2022-06-23 14:04
Can you post the snippet of you code where you are throwing exception? Is there a requirement for you to throw an exception? If not and if you are using implementation of IApiKeyProvider then you can just return null for invalid match.

On other note, have you tried with only setting the status code to 401 i.e. just the 1st line on the above code snippet?

**Comment by eduard-tapkey** [comment] 2022-06-23 17:38
When I use only 1st line of the code, it returns 500. So setting seems to be ignored.

Here is implementation of IApiKeyProvider, where I am throwing an exception. The reason why I am not returning null is to explain also what is wrong with ApiKey in this case

```
		public async Task<IApiKey> ProvideAsync(string key)
		{
			if (key == null)
			{
				throw new UnauthorizedException("No ApiKey is defined");
			}

			var apiKey = new ApiKey(key);

			if (!apiKey.IsValid)
			{
				throw new UnauthorizedException("ApiKey is not valid");
			}

			return apiKey;
		}
```

I would expect that such exception would translate to 401, but if not, I would like to translate it. 
If it is not possible, I cam return null, but can I somehow pass error message to it?

**Comment by mihirdilip** [comment] 2022-06-23 18:13
Do not implement `IApiKeyProvider` and try implementing the `OnValidateKey` delegate on the Events instead. Check it out [here on the samples](https://github.com/mihirdilip/aspnetcore-authentication-apikey/blob/6e9e0523564b3d7e44875e2883c47db6e26d60ca/samples/SampleWebApi_6_0/Program.cs#L68).

Cannot remember how the message is returned on the response with `context.ValidationFailed(message)`. If the message is not returned on the response, you might be able to write your message to the response or  add your message as response header.

Hope this helps.

**Comment by eduard-tapkey** [comment] 2022-06-24 06:46
so I assume something like this should do, right? Because it still goes further and returns 500 on further steps (it doesn't fail here)
```
OnValidateKey = context =>
                    {
                        if (context.ApiKey == null)
                        {
                            context.ValidationFailed("No ApiKey defined");
                        }
                        else if (!ApiKey.ValidateApiKey(context.ApiKey))
                        {
                            context.ValidationFailed("ApiKey is not valid");
                        }
                        else
                        {
                            context.ValidationSucceeded();
                        }

                        return Task.CompletedTask;
                    }
```

**Comment by mihirdilip** [comment] 2022-06-24 08:07
Just to double check - you have removed IApiKeyProvider implementation and any path in ApiKey.ValidateApiKey call does not throw any exception?

**Comment by eduard-tapkey** [comment] 2022-06-24 09:41
Yes, correct as you said.
Problem is that there is policy defined with additional Requirements. And these requirements do rely on ApiKey being validated. 
It seems that even when validation has failed, it still continues to requirements and that throws 500 then.
When I remove the policy/requirements, it returns 401. Message is not defined though.

**Comment by mihirdilip** [comment] 2022-06-24 11:02
Good find. So now you know where the problem is. Hopefully you will figure it out to solve it. If you need any help, let me know with the code snippet.

Regarding error message, my understanding is that the message is for logging only and 401 usually don't return any message. However if you want a custom message then perhaps write it to response or use response header.

**Comment by mihirdilip** [comment] 2022-11-22 21:17
Assuming that this is no longer a problem and closing this issue.

**Closed as completed by mihirdilip** 2022-11-22 21:17 UTC
